name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        env:
          DOCKER_HUB_USERNAME: spacez320
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          docker login --password $DOCKER_HUB_TOKEN --username $DOCKER_HUB_USERNAME
          docker build --tag spacez320/matthewandhilary:latest .
          docker push spacez320/matthewandhilary:latest
